name = "saju-app"
type = "javascript"
account_id = "e57ba0a982f96ad9b1e1998baae208ed"
workers_dev = false
route = ""
zone_id = ""

[site]
bucket = "./"
entry-point = ""

[[kv_namespaces]]
binding = "SAJU_USERS"
id = "f2a7b5fab53e477e89f4c6a64dc3aece"
